version: '3'
services:
  # express-server:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - CONN_STR=mongodb://testAdmin:secret@mongodb
  #   # command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testAdmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - type: bind
        source: ./data
        target: /data/db
